version: '3.8'

services:
  postgres:
    image: postgres:15.6
    restart: always
    environment:
      POSTGRES_USER: userdev
      POSTGRES_PASSWORD: userdevpass
      POSTGRES_DB: mini-store
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
